site_name: Proton Irradiation Station at IFJ
theme:
  name: material
  custom_dir: overrides
  language: en

  # Icons
  icon:
    logo: material/library

  features:
    # - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    #- content.tabs.link
    - content.tooltips
    - header.autohide
    #- navigation.expand
    #- navigation.footer
    #- navigation.indexes
    #- navigation.instant
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    #- navigation.tracking
    - search.highlight
    #- search.share
    - search.suggest
    #- toc.follow
    #- toc.integrate
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  logo: img/logo_ifj_kolor.jpg

plugins:
  - search
  - git-revision-date-localized

extra:
  social:
    - icon: fontawesome/solid/paper-plane
      link: mailto:proton.irradiations@ifj.edu.pl
nav:
    - Home: index.md
    - IRRADIATION STATIONS:
        - STATION 1: hall1.md
        - STATION 2: hall2.md
    - How to apply: order.md
    - Contact: contact.md 

